### ISSUE TITLE
JS: Multiple mobile versions give syntax errors after bundeling.

### ISSUE THREAD

**Issue by iJoris** [adams85/bundling#16]
Getting multiple errors from sentry on syntax errors after bundeling.
Just tested on iPhone 11 pro 13.2, and the not-bundeled JS works perfectly, but after bundeling gives a syntax error.
![image](https://user-images.githubusercontent.com/11030139/155840456-b51aab91-1bac-4b9a-a737-7774c5ea13ae.png)
![image](https://user-images.githubusercontent.com/11030139/155840458-52b67d28-acd6-4cde-8058-2a643c5b0792.png)

Code:
`
target.forEach((el)=>{
        if (el.name.includes(',')) {
            const arr=el.name.split(',');
            arr.forEach((str)=>{
                const sec=window.data.find(x=>x.name=== str);
                if (sec) {
                    result.push(sec.id);
                }
            }
            );
        } else {
            result.push(el.id);
        }
    }
    );
    result.forEach((id)=>{
        dowork(id);
    }
    );
}
`

**Comment by iJoris** [comment]
Found out that the problem was Optional chaining.

**Comment by adams85** [comment]
Do I understand correctly that the error occurs in bundled and **minified** files?

If so, which minimizer do you use? NUglify or WebMarkupMin? Do you use ES6 module bundling?

**Comment by iJoris** [comment]
@adams85 Yes, I use WebMarkupMin.
I've tested it with the ES6 package Karambolo.AspNetCore.Bundling.EcmaScript. But no luck.

For now, I've just removed the '?' with simple if statements.

**Comment by adams85** [comment]
*Karambolo.AspNetCore.Bundling.EcmaScript* is for bundling [JavaScript modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). If you doesn't use JavaScript modules, there's no point in consuming this package.

It seems likely that *WebMarkupMin* doesn't handle the optional chaining operator well. However, you can try *NUglify* instead of that. If that doesn't work either, you can even try to add a direct reference to [the latest version (1.17.10) of the NUglify package](https://www.nuget.org/packages/NUglify/1.17.10) to your project because the latest release of *Karambolo.AspNetCore.Bundling.NUglify* references a bit outdated version (1.16.0) of NUglify. (Since a direct reference would force the latest version to be used.)

**Comment by iJoris** [comment]
> force

Cheers, going to try that!
Thanks for the quick replies.

**Comment by iJoris** [comment]
> _Karambolo.AspNetCore.Bundling.EcmaScript_ is for bundling [JavaScript modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). If you doesn't use JavaScript modules, there's no point in consuming this package.
> 
> It seems likely that _WebMarkupMin_ doesn't handle the optional chaining operator well. However, you can try _NUglify_ instead of that. If that doesn't work either, you can even try to add a direct reference to [the latest version (1.17.10) of the NUglify package](https://www.nuget.org/packages/NUglify/1.17.10) to your project because the latest release of _Karambolo.AspNetCore.Bundling.NUglify_ references a bit outdated version (1.16.0) of NUglify. (Since a direct reference would force the latest version to be used.)



Cheers, going to try that!
Thanks for the quick replies.
