### ISSUE TITLE
Does it work with .NET Framework 4.7?

### ISSUE THREAD

**Issue by Gruski** [adams85/bundling#7]
I have an ASP.NET WebForms WebSite project. Will this component work such project for bundling and minification?

**Comment by adams85** [comment]
No, it won't. This lib is for ASP.NET Core only.

For classic ASP.NET projects your best bet is _System.Web.Optimization_. At least, there's a [NuGet package for WebForms](https://www.nuget.org/packages/Microsoft.AspNet.Web.Optimization.WebForms/) so it should work for you. (Cannot say for sure, I've used it only in MVC projects).

**Comment by Gruski** [comment]
That one has not been updated since 2014 and fails on all kinds of modern concepts: i.e. css props, async/await, etc. so it is completely useless for css and javascript minification at all levels. Do you know of any modern minifiers that work well with ASP.NET WebForms?

**Comment by adams85** [comment]
I don't know of other bundling solutions for classic ASP.NET.

_System.Web.Optimization_ may not be totally hopeless though. It is extensible to a fair degree. E.g. [you can define custom bundle types](https://github.com/scott-xu/System.Web.Optimization.Less), so probably it can be integrated with libs like _NUglify_ or _LibSassHost_.

Another option might be to backport my lib. It should be doable as it supports Netstandard 2.0 which is available on NET 4.6.1 or later. There are relatively few ASP.NET Core specific parts, which can be replaced with some effort. This would take definitely more work than tweaking _System.Web.Optimization_ though (and TBH, I don't see too much value in this when classic .NET is virtually considered as legacy).

**Comment by Gruski** [comment]
Well I don't have the resources to extend System.Web.Optimization. Looking for a done solution not something that needs time investment. It would be good if you backported your lib. Although .NET is considered legacy for new development, there are still many huge projects built on it that will not go away any time soon and need to use new CSS and ES6 features. Right now we are not minifying because there is nothing out there for .NET that does it.

**Comment by adams85** [comment]
I understand your situation but I'm not sure where you are going with this. Of course, I could backport my lib if I wanted to. But that'd take a significant amount of effort for something I'm not in need of.

In this repo I shared some high quality software components with the public for free. But these were created because I needed them or, at times, for fun. Backporting this lib neither would have any value, nor would be fun for me. So I'm sad to say that this won't happen unless you give me some incentive.

AFAIK, there's no out-of-the-box solution to your problem. If you want a solution, you'll need investment in one way or the other. If you stick to using this lib, I'm open to further discussion. In this case, please give me your email address and let's continue it privately.
